version: "2"
services:
    db:
        image: postgres:9.5
        environment:
            POSTGRES_USER: flask
            POSTGRES_PASSWORD: '123456'
            POSTGRES_DB: flask
            PGDATA: /var/lib/postgresql/data
        restart: always

    redis:
        image: redis:3.2
        restart: always

    api:
        expose:
            - 5000
        depends_on:
             - db
             - redis
        restart: always
